// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCSVProcessorInterface is an autogenerated mock type for the CSVProcessorInterface type
type MockCSVProcessorInterface struct {
	mock.Mock
}

type MockCSVProcessorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCSVProcessorInterface) EXPECT() *MockCSVProcessorInterface_Expecter {
	return &MockCSVProcessorInterface_Expecter{mock: &_m.Mock}
}

// ProcessStream provides a mock function with given fields: ctx, uploadID, reader
func (_m *MockCSVProcessorInterface) ProcessStream(ctx context.Context, uploadID string, reader io.Reader) error {
	ret := _m.Called(ctx, uploadID, reader)

	if len(ret) == 0 {
		panic("no return value specified for ProcessStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, uploadID, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCSVProcessorInterface_ProcessStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessStream'
type MockCSVProcessorInterface_ProcessStream_Call struct {
	*mock.Call
}

// ProcessStream is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - reader io.Reader
func (_e *MockCSVProcessorInterface_Expecter) ProcessStream(ctx interface{}, uploadID interface{}, reader interface{}) *MockCSVProcessorInterface_ProcessStream_Call {
	return &MockCSVProcessorInterface_ProcessStream_Call{Call: _e.mock.On("ProcessStream", ctx, uploadID, reader)}
}

func (_c *MockCSVProcessorInterface_ProcessStream_Call) Run(run func(ctx context.Context, uploadID string, reader io.Reader)) *MockCSVProcessorInterface_ProcessStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockCSVProcessorInterface_ProcessStream_Call) Return(_a0 error) *MockCSVProcessorInterface_ProcessStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCSVProcessorInterface_ProcessStream_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockCSVProcessorInterface_ProcessStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCSVProcessorInterface creates a new instance of MockCSVProcessorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCSVProcessorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCSVProcessorInterface {
	mock := &MockCSVProcessorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
