// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/grachmannico95/flip-test-be/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddTransaction provides a mock function with given fields: ctx, uploadID, tx, lineNumber
func (_m *MockRepository) AddTransaction(ctx context.Context, uploadID string, tx domain.Transaction, lineNumber int) error {
	ret := _m.Called(ctx, uploadID, tx, lineNumber)

	if len(ret) == 0 {
		panic("no return value specified for AddTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Transaction, int) error); ok {
		r0 = rf(ctx, uploadID, tx, lineNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransaction'
type MockRepository_AddTransaction_Call struct {
	*mock.Call
}

// AddTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - tx domain.Transaction
//   - lineNumber int
func (_e *MockRepository_Expecter) AddTransaction(ctx interface{}, uploadID interface{}, tx interface{}, lineNumber interface{}) *MockRepository_AddTransaction_Call {
	return &MockRepository_AddTransaction_Call{Call: _e.mock.On("AddTransaction", ctx, uploadID, tx, lineNumber)}
}

func (_c *MockRepository_AddTransaction_Call) Run(run func(ctx context.Context, uploadID string, tx domain.Transaction, lineNumber int)) *MockRepository_AddTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Transaction), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_AddTransaction_Call) Return(_a0 error) *MockRepository_AddTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddTransaction_Call) RunAndReturn(run func(context.Context, string, domain.Transaction, int) error) *MockRepository_AddTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUpload provides a mock function with given fields: ctx, uploadID
func (_m *MockRepository) CreateUpload(ctx context.Context, uploadID string) error {
	ret := _m.Called(ctx, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for CreateUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uploadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUpload'
type MockRepository_CreateUpload_Call struct {
	*mock.Call
}

// CreateUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
func (_e *MockRepository_Expecter) CreateUpload(ctx interface{}, uploadID interface{}) *MockRepository_CreateUpload_Call {
	return &MockRepository_CreateUpload_Call{Call: _e.mock.On("CreateUpload", ctx, uploadID)}
}

func (_c *MockRepository_CreateUpload_Call) Run(run func(ctx context.Context, uploadID string)) *MockRepository_CreateUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_CreateUpload_Call) Return(_a0 error) *MockRepository_CreateUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateUpload_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_CreateUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, uploadID
func (_m *MockRepository) GetBalance(ctx context.Context, uploadID string) (int64, error) {
	ret := _m.Called(ctx, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, uploadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, uploadID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uploadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockRepository_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
func (_e *MockRepository_Expecter) GetBalance(ctx interface{}, uploadID interface{}) *MockRepository_GetBalance_Call {
	return &MockRepository_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, uploadID)}
}

func (_c *MockRepository_GetBalance_Call) Run(run func(ctx context.Context, uploadID string)) *MockRepository_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetBalance_Call) Return(_a0 int64, _a1 error) *MockRepository_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetBalance_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockRepository_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssues provides a mock function with given fields: ctx, uploadID, page, perPage, status
func (_m *MockRepository) GetIssues(ctx context.Context, uploadID string, page int, perPage int, status *domain.TransactionStatus) ([]domain.IssueTransaction, int, error) {
	ret := _m.Called(ctx, uploadID, page, perPage, status)

	if len(ret) == 0 {
		panic("no return value specified for GetIssues")
	}

	var r0 []domain.IssueTransaction
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, *domain.TransactionStatus) ([]domain.IssueTransaction, int, error)); ok {
		return rf(ctx, uploadID, page, perPage, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, *domain.TransactionStatus) []domain.IssueTransaction); ok {
		r0 = rf(ctx, uploadID, page, perPage, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.IssueTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, *domain.TransactionStatus) int); ok {
		r1 = rf(ctx, uploadID, page, perPage, status)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, *domain.TransactionStatus) error); ok {
		r2 = rf(ctx, uploadID, page, perPage, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssues'
type MockRepository_GetIssues_Call struct {
	*mock.Call
}

// GetIssues is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - page int
//   - perPage int
//   - status *domain.TransactionStatus
func (_e *MockRepository_Expecter) GetIssues(ctx interface{}, uploadID interface{}, page interface{}, perPage interface{}, status interface{}) *MockRepository_GetIssues_Call {
	return &MockRepository_GetIssues_Call{Call: _e.mock.On("GetIssues", ctx, uploadID, page, perPage, status)}
}

func (_c *MockRepository_GetIssues_Call) Run(run func(ctx context.Context, uploadID string, page int, perPage int, status *domain.TransactionStatus)) *MockRepository_GetIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(*domain.TransactionStatus))
	})
	return _c
}

func (_c *MockRepository_GetIssues_Call) Return(_a0 []domain.IssueTransaction, _a1 int, _a2 error) *MockRepository_GetIssues_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetIssues_Call) RunAndReturn(run func(context.Context, string, int, int, *domain.TransactionStatus) ([]domain.IssueTransaction, int, error)) *MockRepository_GetIssues_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpload provides a mock function with given fields: ctx, uploadID
func (_m *MockRepository) GetUpload(ctx context.Context, uploadID string) (*domain.Upload, error) {
	ret := _m.Called(ctx, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for GetUpload")
	}

	var r0 *domain.Upload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Upload, error)); ok {
		return rf(ctx, uploadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Upload); ok {
		r0 = rf(ctx, uploadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Upload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uploadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpload'
type MockRepository_GetUpload_Call struct {
	*mock.Call
}

// GetUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
func (_e *MockRepository_Expecter) GetUpload(ctx interface{}, uploadID interface{}) *MockRepository_GetUpload_Call {
	return &MockRepository_GetUpload_Call{Call: _e.mock.On("GetUpload", ctx, uploadID)}
}

func (_c *MockRepository_GetUpload_Call) Run(run func(ctx context.Context, uploadID string)) *MockRepository_GetUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUpload_Call) Return(_a0 *domain.Upload, _a1 error) *MockRepository_GetUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUpload_Call) RunAndReturn(run func(context.Context, string) (*domain.Upload, error)) *MockRepository_GetUpload_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementProcessedRows provides a mock function with given fields: ctx, uploadID
func (_m *MockRepository) IncrementProcessedRows(ctx context.Context, uploadID string) error {
	ret := _m.Called(ctx, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementProcessedRows")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uploadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IncrementProcessedRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementProcessedRows'
type MockRepository_IncrementProcessedRows_Call struct {
	*mock.Call
}

// IncrementProcessedRows is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
func (_e *MockRepository_Expecter) IncrementProcessedRows(ctx interface{}, uploadID interface{}) *MockRepository_IncrementProcessedRows_Call {
	return &MockRepository_IncrementProcessedRows_Call{Call: _e.mock.On("IncrementProcessedRows", ctx, uploadID)}
}

func (_c *MockRepository_IncrementProcessedRows_Call) Run(run func(ctx context.Context, uploadID string)) *MockRepository_IncrementProcessedRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IncrementProcessedRows_Call) Return(_a0 error) *MockRepository_IncrementProcessedRows_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IncrementProcessedRows_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_IncrementProcessedRows_Call {
	_c.Call.Return(run)
	return _c
}

// IsEventProcessed provides a mock function with given fields: ctx, eventID
func (_m *MockRepository) IsEventProcessed(ctx context.Context, eventID string) (bool, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for IsEventProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEventProcessed'
type MockRepository_IsEventProcessed_Call struct {
	*mock.Call
}

// IsEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockRepository_Expecter) IsEventProcessed(ctx interface{}, eventID interface{}) *MockRepository_IsEventProcessed_Call {
	return &MockRepository_IsEventProcessed_Call{Call: _e.mock.On("IsEventProcessed", ctx, eventID)}
}

func (_c *MockRepository_IsEventProcessed_Call) Run(run func(ctx context.Context, eventID string)) *MockRepository_IsEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_IsEventProcessed_Call) Return(_a0 bool, _a1 error) *MockRepository_IsEventProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsEventProcessed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_IsEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEventProcessed provides a mock function with given fields: ctx, eventID
func (_m *MockRepository) MarkEventProcessed(ctx context.Context, eventID string) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEventProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEventProcessed'
type MockRepository_MarkEventProcessed_Call struct {
	*mock.Call
}

// MarkEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockRepository_Expecter) MarkEventProcessed(ctx interface{}, eventID interface{}) *MockRepository_MarkEventProcessed_Call {
	return &MockRepository_MarkEventProcessed_Call{Call: _e.mock.On("MarkEventProcessed", ctx, eventID)}
}

func (_c *MockRepository_MarkEventProcessed_Call) Run(run func(ctx context.Context, eventID string)) *MockRepository_MarkEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_MarkEventProcessed_Call) Return(_a0 error) *MockRepository_MarkEventProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkEventProcessed_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_MarkEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUploadStatus provides a mock function with given fields: ctx, uploadID, status
func (_m *MockRepository) UpdateUploadStatus(ctx context.Context, uploadID string, status domain.UploadStatus) error {
	ret := _m.Called(ctx, uploadID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUploadStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UploadStatus) error); ok {
		r0 = rf(ctx, uploadID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateUploadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUploadStatus'
type MockRepository_UpdateUploadStatus_Call struct {
	*mock.Call
}

// UpdateUploadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - status domain.UploadStatus
func (_e *MockRepository_Expecter) UpdateUploadStatus(ctx interface{}, uploadID interface{}, status interface{}) *MockRepository_UpdateUploadStatus_Call {
	return &MockRepository_UpdateUploadStatus_Call{Call: _e.mock.On("UpdateUploadStatus", ctx, uploadID, status)}
}

func (_c *MockRepository_UpdateUploadStatus_Call) Run(run func(ctx context.Context, uploadID string, status domain.UploadStatus)) *MockRepository_UpdateUploadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.UploadStatus))
	})
	return _c
}

func (_c *MockRepository_UpdateUploadStatus_Call) Return(_a0 error) *MockRepository_UpdateUploadStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateUploadStatus_Call) RunAndReturn(run func(context.Context, string, domain.UploadStatus) error) *MockRepository_UpdateUploadStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
